Repository jina-ai/examples, pull requests merged in 2020-11, with the labels that each got.

#263 Example southpark distributed
  southpark-search/tests/distributed/.env
  southpark-search/tests/distributed/Dockerfile
  southpark-search/tests/distributed/docker-compose.yml
  southpark-search/tests/distributed/flow-query.yml
  southpark-search/tests/distributed/requirements.txt
  southpark-search/tests/distributed/test_integration.sh
Labels: hacktoberfest, hacktoberfest2020

#268 test: run southpark distributed on jina master
  southpark-search/tests/distributed/requirements.txt
Labels: hacktoberfest, hacktoberfest2020

#269 docs: instructions to add test for examples
  README.md
Labels: hacktoberfest, hacktoberfest2020

#267 feat: adjust multimodal encoder
  multimodal-search-tirg/TirgMultimodalEncoder /__init__.py
  multimodal-search-tirg/tirg.ipynb
Labels: hacktoberfest, hacktoberfest2020

#270 test: upgrade multires lyrics to 0.7.4
  multires-lyrics-search/requirements.txt
  multires-lyrics-search/tests/query_results.json
  multires-lyrics-search/tests/test_multireslyrics.py
Labels: dependencies

#258 chore: removing duplicate folder
  mfcc-audio-search/flows/flow-query.yml
Labels: hacktoberfest, hacktoberfest2020

#262 Docs readme revamp
  README.md
Labels: hacktoberfest, hacktoberfest2020

#273 docs(readme): polish wording
  README.md
Labels: hacktoberfest, hacktoberfest2020

#274 test: runs with jina and jinad main
  southpark-search/tests/distributed/Dockerfile
  southpark-search/tests/distributed/test_integration.sh
Labels: hacktoberfest, hacktoberfest2020

#280 feat: add warning for existing workspace
  audio-search-mfcc/app.py
  audio-search/app.py
  face-db-search/app.py
  faiss-search/app.py
  fashion-example-query/fashion/app.py
  flower-search/app.py
  io-mock-app/app.py
  mnist-with-mindspore/app.py
  multilingual-search/app.py
  multires-lyrics-search/app.py
  news_search/app.py
  object-search/app.py
  pokedex-with-bit/app.py
  southpark-search/app.py
  tumblr-gif-search/app.py
  urbandict-search/app.py
Labels: hacktoberfest, hacktoberfest2020

#282 Refactor Pokedex directories, files
  pokedex-with-bit/README.md
  pokedex-with-bit/app.py
  pokedex-with-bit/flows/index.yml
  pokedex-with-bit/flows/query.yml
  pokedex-with-bit/make_html.py
Labels: hacktoberfest, hacktoberfest2020

#281 test: add incremental indexing example
  southpark-incremental-indexing/README.md
  southpark-incremental-indexing/app.py
  southpark-incremental-indexing/flow-index.yml
  southpark-incremental-indexing/flow-query.yml
  southpark-incremental-indexing/get_data.sh
  southpark-incremental-indexing/pods/encode.yml
  southpark-incremental-indexing/pods/extract.yml
  southpark-incremental-indexing/pods/index.yml
  southpark-incremental-indexing/pods/index_cache.yml
  southpark-incremental-indexing/pods/text_loader.py
  southpark-incremental-indexing/prepare_data.py
  southpark-incremental-indexing/requirements.txt
  southpark-incremental-indexing/tests/data-index-1.csv
  southpark-incremental-indexing/tests/data-index-2.csv
  southpark-incremental-indexing/tests/test_southparksearch_incremental.py
  southpark-search/README.md
Labels: hacktoberfest, hacktoberfest2020

#291 feat: add shards and parallel
  multimodal-search-tirg/README.MD
  multimodal-search-tirg/app.py
  multimodal-search-tirg/flow-index.yml
  multimodal-search-tirg/flow-query.yml
  multimodal-search-tirg/pods/doc.yml
  multimodal-search-tirg/pods/image-read.yml
  multimodal-search-tirg/pods/normalize.yml
  multimodal-search-tirg/pods/vec.yml
Labels: hacktoberfest, hacktoberfest2020

#277 feat: add terraform script for southpark
  southpark-search/tests/distributed/README.md
  southpark-search/tests/distributed/push.sh
  southpark-search/tests/distributed/terraform.tf
  southpark-search/tests/distributed/variables.tf
Labels: documentation, enhancement, terraform
